Imports System.Xml.Serialization
Imports Biopax
Imports Microsoft.VisualBasic.DocumentFormat.RDF

Public Class Ontology : Inherits OwlOntology
    Public Property [date] As EntityProperties.date
    Public Property hasOBOFormatVersion As hasOBOFormatVersion
    <XmlElement("auto-generated-by")> Public Property autoGeneratedBy As RDFProperty
    <XmlElement("saved-by")> Public Property SavedBy As RDFProperty
    <XmlElement("default-namespace")> Public Property DefaultNamespace As RDFProperty
    Public Property versionIRI As RDFProperty
End Class

Public Class hasOBOFormatVersion : Inherits EntityProperty

End Class